# Generated by Django 5.1.7 on 2025-03-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tc',
            new_name='terms_conditions',
        ),
    ]
