# Generated by Django 5.1.7 on 2025-06-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_rename_tc_user_terms_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='tempuser', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
